config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/landscape', to: 'application#landscape', as: :landscape
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def landscape
    @dimension = (params[:dimension] || 5).to_i

    cities = (0..@dimension - 1).to_a

    @distances = Array.new(@dimension) { Array.new(@dimension) { 0 }}

    @dimension.times { |i|  @dimension.times {|j|  @distances[i][j] = i < j ? rand(100) : @distances[j][i] }}

    all_solutions = cities.permutation(@dimension).to_a

    @solutions_by_cities = {}
    all_solutions.each_with_index do |solution, i|
      @solutions_by_cities[solution.join('')] = solution.each_cons(2).map { |a, b| @distances[a][b] }.sum + @distances[solution.first][solution.last]
    end

    render 'layouts/landscape'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TspLandscape</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "highcharts", "chartkick" %>
    <link href='https://fonts.googleapis.com/css?family=Raleway|Montserrat:400,700|Roboto:400,300,300italic,400italic,500' rel='stylesheet' type='text/css'>
    <link href="https://fonts.googleapis.com/css?family=Cousine|Cutive+Mono|Fira+Mono|PT+Mono|Source+Code+Pro|VT323|Voces" rel="stylesheet">

    <!--<link rel="stylesheet" type="text/css" href="css/montserrat/montserrat.css">-->
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdn.linearicons.com/free/1.0.0/icon-font.min.css">

    <!--  <link rel="stylesheet" type="text/css" href="css/jquery.mCustomScrollbar.css">
      <link rel="stylesheet" type="text/css" href="css/structure.css">
      <link rel="stylesheet" type="text/css" href="css/style.css">
      <link rel="stylesheet" type="text/css" href="css/style-searchpage.css">
      <link rel="stylesheet" type="text/css" href="css/theme-light.css">-->

    <script src="https://code.jquery.com/jquery-2.2.3.min.js" integrity="sha256-a23g1Nt4dtEYOj7bR+vTu7+T8VP13humZFBJNIYoEJo=" crossorigin="anonymous"></script>
    <script type="text/javascript" src="https://code.jquery.com/ui/1.12.0-beta.1/jquery-ui.min.js"></script>

    <script type="application/javascript" src="https://cdn.datatables.net/buttons/1.2.2/js/dataTables.buttons.min.js"></script>
    <script type="application/javascript" src="//cdn.datatables.net/buttons/1.2.2/js/buttons.colVis.min.js"></script>

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/landscape.html.erb
<html>
  <head>
    <style>
      table, th, td {
        border: 1px solid black;
        border-collapse: collapse;
      }
    </style>
  </head>
  <body>
    <div>
      <div>
        <%= line_chart [{ name: 'Zgjidhjet',  data: @solutions_by_cities }] %>
      </div>

      <div>
        <form action="<%= landscape_path %>">

          <label>Numri i qyteteve:</label>
          <input name="dimension" value="<%= @dimension %>" type="text">

          <button type="submit">Ndrysho</button>

          <label>Numri i zgjidhjeve:</label>
          <input readonly value="<%= (1..@dimension).inject(:*) || 1 %>" type="text">

        </form>
      </div>
    </div>
    <br>
    <div>
      <p>Distancat mes qyteteve:</p>
      <table style="width:25%">

        <% @distances.each do |row| %>
          <tr> <% row.each do |val| %> <td> <%= val %> </td> <% end %> </tr>
        <% end %>

      </table>
    </div>
  </body>
</html>